-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxyBdwirh4qfexMSc
dYhxbBsuTTebY5zKv4fmpxoYrregCgYIKoZIzj0DAQehRANCAATOdIZrG7XzLtfF
vVSxiFNjlopDkvPFJ2kvnDPPQKzd6wCZhOjP/3lMPXU3FH/8rypuxq8SPWNm0kh3
5F7SZDOd
-----END PRIVATE KEY-----